excluded_buoys:
  - ""

buoy_names:
  - "surmark950410" # red, conical
  - "surmark46104"  # white, tophat
  - "surmark950400" # green, tophat
  - "yellow_totem"
  - "black_totem"
  - "blue_totem"
  - "green_totem"
  - "red_totem"
  - "polyform"  # black sphere
  - "scan_buoy" # code sequence flashing buoy
